SELECT * FROM voo 
	INNER JOIN aeroporto on idAEROPORTO_ORIGEM = idAEROPORTO AND idAEROPORTO_DESTINO = idAEROPORTO 
    WHERE HORARIO_PARTIDA LIKE '%2017-09-19%';

SELECT * FROM voo WHERE HORARIO_PARTIDA LIKE '%2017-09-19%' INNER JOIN aeroporto on idAEROPORTO_ORIGEM = 2